name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd ui/v2/frontend
        npm install

    - name: Build
      run: |
        cd ui/v2/frontend
        npm run build-preview

    - name: Archive build folder
      uses: actions/upload-artifact@v2
      with:
        name: frontend-app
        path: ui/v2/frontend/build

  build:
    needs: build-frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20', '1.21']
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v2

    - name: Download frontend build
      uses: actions/download-artifact@v2
      with:
        name: frontend-app
        path: ui/v2/frontend/build

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
